builds:
  - binary: saw
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archive:
  format: tar.gz
  files:
    - LICENSE

fpm:
  vendor: Tyler Brock
  homepage: https://github.com/TylerBrock/saw
  maintainer: Tyler Brock <tyler.brock@gmail.com>
  description: Fast, multipurpose tool for AWS CloudWatch Logs
  license: MIT
  formats:
    - deb
    - rpm
