builds:
  - binary: saw
    goos:
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archive:
  format: tar.gz
  files:
    - LICENSE
